# Generated by Django 4.2.2 on 2023-07-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwd', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(max_length=20)),
            ],
        ),
    ]
