# Generated by Django 4.2.2 on 2023-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
